/**
 * A majority of this code was written by AI.
 * 
 * Script Name: live_preview.dart
 * Description: 
 *   A widget that displays a near real-time camera feed by periodically 
 *   reading a BMP file generated by the camera backend.
 */

import 'dart:async';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:path/path.dart' as p;

class LivePreview extends StatefulWidget {
  final String? projectRoot;
  const LivePreview({super.key, this.projectRoot});

  @override
  State<LivePreview> createState() => _LivePreviewState();
}

class _LivePreviewState extends State<LivePreview> {
  static const String _relativePath = 'images/live/live.bmp';
  late final String _path;
  Timer? _timer;
  Uint8List? _bytes;

  String _resolveLivePath() {
    if (widget.projectRoot != null) {
      return p.join(widget.projectRoot!, _relativePath);
    }

    final cwd = Directory.current.path;

    final direct = File(_relativePath);
    if (direct.existsSync()) return direct.path;

    Directory probe = Directory(cwd);
    for (int i = 0; i < 6; i++) {
      final candidate = File(p.join(probe.path, _relativePath));
      if (candidate.existsSync()) return candidate.path;

      final next = probe.parent;
      if (next.path == probe.path) break;
      probe = next;
    }

    // Fallback to an absolute path relative to the current working directory.
    return p.normalize(p.join(cwd, _relativePath));
  }

  @override
  void initState() {
    super.initState();
    _path = _resolveLivePath();
    _timer = Timer.periodic(const Duration(milliseconds: 50), (_) async {
      try {
        final b = await File(_path).readAsBytes();
        if (!mounted) return;
        // Always update state to refresh the image
        setState(() => _bytes = b);
      } catch (_) {}
    });
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_bytes == null) {
      return const Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 8),
            Text(
              'Waiting for camera...',
              style: TextStyle(color: Colors.white),
            ),
          ],
        ),
      );
    }
    return GestureDetector(
      onTap: () {},
      child: FittedBox(
        fit: BoxFit.cover,
        child: Image.memory(
          _bytes!,
          gaplessPlayback: true,
          filterQuality: FilterQuality.low,
        ),
      ),
    );
  }
}
